### ISSUE TITLE
Consolidating taskcluster queries

### ISSUE THREAD

**Issue by srfraser** [mozilla-releng/measuring_ci#11]
How much is it worth re-using work in https://github.com/srfraser/taskhuddler for this repo? We could fold changes here into there, or vice versa, depending on what model people find most useful for making the taskcluster queries.

Taskhuddler has a more pythonic layer over taskcluster-client.py, allowing statements like `graph = TaskGraph('M5hSue6oRSu_klunMRHolg')`

**Comment by Callek** [comment]
I have no objections to using taskhuddler, I think when I tried initially I found some rough edges so decided to go straight for the API that I knew slightly better. But I'd be more than happy using that tool.
