### ISSUE TITLE
Don't use pipfile.lock in repo..

### ISSUE THREAD

**Issue by Callek** [mozilla-releng/measuring_ci#30]
Hey @srfraser , what do you think..

I lean toward not using Pipfile.lock here due primarily to https://github.com/pyupio/pyup/issues/197 I'm feeling it just isn't stable enough with tools to natively use for our project. -- I'd rather only use one dependency format (requirements or pipfile) but I don't want to lose pyup...

**Comment by srfraser** [comment]
I'm happy to remove the lock file, especially as things are churning quite rapidly.

**Comment by srfraser** [comment]
This was done
