### ISSUE TITLE
New architecture for task data collection

### ISSUE THREAD

**Issue by srfraser** [mozilla-releng/measuring_ci#436]
The existing data collection method works, but is cumbersome. 

1. There are significant delays between a task completing and data arriving.
2. There is currently an estimate of when a task group has finished, based on time since it started. This isn't entirely reliable.
3. We have to explicitly find task groups to monitor

# Proposal

Monitor the pulse messages for the following exchanges:
* exchange/taskcluster-queue/v1/task-completed
* exchange/taskcluster-queue/v1/task-failed
* exchange/taskcluster-queue/v1/task-exception
* exchange/taskcluster-queue/v1/artifact-created
* exchange/taskcluster-queue/v1/task-group-resolved

This will get us data with low latency about task and artifact progress.

The pulse messages don't contain everything we need at the moment. Here is an example task-completed message:

```
{
    "status": {
        "taskId": "Na7xQRj3TPWhJQorO9R55w",
        "provisionerId": "aws-provisioner-v1",
        "workerType": "gecko-t-linux-xlarge",
        "schedulerId": "gecko-level-1",
        "taskGroupId": "YYSylG-kSimUTa4o8bUTyg",
        "deadline": "2019-02-19T09:12:31.672Z",
        "expires": "2019-03-04T09:12:31.672Z",
        "retriesLeft": 5,
        "state": "completed",
        "runs": [
            {
                "runId": 0,
                "state": "completed",
                "reasonCreated": "scheduled",
                "reasonResolved": "completed",
                "workerGroup": "us-east-1",
                "workerId": "i-02f5e6ccddbba9f9a",
                "takenUntil": "2019-02-18T10:32:21.384Z",
                "scheduled": "2019-02-18T09:41:34.093Z",
                "started": "2019-02-18T09:41:34.531Z",
                "resolved": "2019-02-18T10:25:20.188Z"
            }
        ]
    },
    "runId": 0,
    "workerGroup": "us-east-1",
    "workerId": "i-02f5e6ccddbba9f9a",
    "version": 1
}
```

There's not enough here to classify the task for our needs, and possibly not in the full task definition, either, so I propose adding classification data to the task's tags, and then getting those tags added to the pulse messages. 

### project

mozilla-central, integration/autoland, and so on. This is to allow us to:
1.  Filter out maple, oak and other project branches if needed
2. Easily allow queries for 'all CI/Release/Cron tasks for betas' and similar.

### product
To allow grouping of results by firefox, fennec, fenix, thunderbird and any others that may appear.

### platform
To allow grouping of results by target platform, rather than the platform used for a particular step. This means that if we end up cross-compiling, or running all tests on one platform, then they can be correctly categorised as existing because 'platform A' was chosen as a target, and the costs breakdown becomes useful.

### kind

Allows grouping of results to see the largest cost components of particular types of task. Some examples might be grouping the release tasks together to provide an overview of costs to promote & ship a build; the trend in costs of tests; duration of builds.

### purpose

Possibly only connected to task groups, the purpose would record whether we were attempting a release promotion, an on-push CI build, a cron automation task, or other task group goal.

### artifact size

Only for artifact-created messages, record the size of the artifact being uploaded. We may need special consideration for live logs, so perhaps the size is only included if the location is the final storage place.

### artifact expiry

To enable cost estimates of the artifact's full life cycle.

### Example of modified task-completed message.
```
{
    "status": {
        ... # as before
    },
   "tags": {
       "project": "mozilla-central",
       "product": "firefox",
       "platform": "linux64",
       "kind": "test"
   }
    "runId": 0,
    "workerGroup": "us-east-1",
    "workerId": "i-02f5e6ccddbba9f9a",
    "version": 1
}
```

### Add correct tags to a task definition

1. project can be inserted from config.params['project']
2. kind can be easily copied from elsewhere in the task definition

#### platform
1. Add 'platform' tags to build tasks, and have downstream tasks inherit from those
2. Anything else gets a default platform (such as source linting) to indicate it's not platform specific.

#### product

There are release product fields but they are not always used, as they are only intended for specific purposes. They could be filled out in all cases, but I don't yet know if there will be consequences for downstream automation.

The value could be passed in as a mach parameter during taskgraph generation, and recorded. This has the advantage of being clearer, but also involves changing every call to generate a task graph.

It could also be set during the target_tasks calls, which assumes that each target_tasks method only has one product associated with it. This is probably true for nightlies and releases, although it may not always be. This seems an unwise assumption for CI builds.

#### purpose

Closely related to the target_tasks_method, so should ideally be set there, or simply record the target_tasks_method and attempt to translate it into a human-friendly string later.

#### Other Questions

Should there be a generic tagging transform, along the same model as name_sanity.py? 

### Add tags to pulse messages

[See Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1530644)

### Set up telemetry

There is documentation around [sending a custom ping](https://docs.telemetry.mozilla.org/cookbooks/new_ping.html?highlight=non,teleme#sending-a-custom-ping). We will need to specify the schema to be used for tasks and artifacts, and get those updated. 

The pipeline can also have post-processing if any is needed, and the resultant files will then be visible through STMO alongside the existing data sets, and others used for business decisions.

We would need to:
1. Assess the queries we would use to show the data, in order to highlight any missing fields we need adding.
2. Determine the schema to be used for the task-* and artifact-* messages 
3. Work out if the task-group-resolved messages would add value to the results we could display.
4. Determine if any post-processing is required

#### Example post-processing

* For each task, extract workerType, compare to costs database and add a cost field.
* For each artifact, consult task/artifact expiry and estimate costs

#### Example Queries

* for task with kind 'test', sum duration by 
* for task with taskgroupid, search matching artifacts and sum sizes.
* For all beta releases, calculate release promotion costs (sum costs of these task kinds)

### Add a consumer

A new service will be required to reliably consume the pulse messages, reformat the data, and submit it to to telemetry. It would need to be always-on to cope with the volume of messages, as the message queue would quickly exceed maximum size during any downtime, and be closed, resulting in missed data. This service would need to be developed and managed - presumably by RelEng and RelOps respectively.

Would we need a catch-up mechanism the service is unavailable for a period of time - perhaps using the old method of listTaskGroup calls?

**Comment by srfraser** [comment]
Do you have any thoughts, @nthomas-mozilla @catlee ?

**Comment by Callek** [comment]
I'm just going to briefly chime in, that with TC we guarantee "at least once" delivery. So we have the possibility to get duplicate messages. Whatever code consumes these should account for that and not cause duplicate data in our DB.

**Comment by nthomas-mozilla** [comment]
I like this proposal. Some notes
* It would be useful to also include a little more information about tasks in the custom ping. For example, the label and test-type tags. This would let us drill in another layer of detail, particularly in the release graphs. Or does `kind` take a wide range of values there, in contrast to build/test/<assorted misc> for on-push ?
* Maybe rename `purpose` to `initiated-by`. I'm assuming the values are like push, promote_firefox, cron_<foo>
* a generic tagging transform is a great idea to ensure some default values

Backfill is tricky. I'm wary of a fallback system processing data differently to the main one due to code divergence or using a different data source. Can we have large, durable, pulse queues to handle our system outages ? Otherwise we might look at a high-availability buffer that consumes pulse messages and stashes them, eg multi-homed in separate cloud services. This might help with reprocessing messages when we notice bugs too.

**Comment by srfraser** [comment]
> I like this proposal. Some notes
> 
>     * It would be useful to also include a little more information about tasks in the custom ping. For example, the label and test-type tags. This would let us drill in another layer of detail, particularly in the release graphs. Or does `kind` take a wide range of values there, in contrast to build/test/ for on-push ?

I think you're right that we need the label, or perhaps a version of the label with chunking removed. I'm not sure how reliable that suffix removal would be, though.

>     * Maybe rename `purpose` to `initiated-by`. I'm assuming the values are like push, promote_firefox, cron_foo

+1 for the rename, and to the values. The current set of target_tasks labels are:
```ash_tasks
codereview
cron_bouncer_check
customv8_update
default   # This is the CI one
file_update
graphics_tasks
mochitest_valgrind
mozilla_beta_tasks
mozilla_esr60_tasks
mozilla_release_tasks
nightly_asan
nightly_desktop
nightly_fennec
nightly_linux
nightly_macosx
nightly_win32
nightly_win64
nightly_win64_aarch64
pine_tasks
pipfile_update
promote_desktop
promote_fennec
push_desktop
release_simulation
searchfox_index
ship_desktop
ship_fennec
staging_release_builds
try_tasks
```
 
> Backfill is tricky. I'm wary of a fallback system processing data differently to the main one due to code divergence or using a different data source. Can we have large, durable, pulse queues to handle our system outages ? Otherwise we might look at a high-availability buffer that consumes pulse messages and stashes them, eg multi-homed in separate cloud services. This might help with reprocessing messages when we notice bugs too.

The pulse queue would have to be very large compared to the others - I think it took about an hour to reach the default limit during my testing. I think it'll be relatively easy to deduplicate later on based on (taskId, runId) so we could just consume multiple times and deduplicate later. We do this with the current parqet collator script.
