### ISSUE TITLE
Send the data using a custom ping rather than presenting a parquet file.

### ISSUE THREAD

**Issue by srfraser** [mozilla-releng/measuring_ci#51]
https://docs.telemetry.mozilla.org/cookbooks/new_ping.html

We could still use the parquet file for recording results and deduplicating the data we send, but we should use the generic ingestion method.

**Comment by srfraser** [comment]
We'll need to submit a schema definition for this, do we consider the per-push costs table stable enough to do that, now? @nthomas-mozilla @Callek

**Comment by nthomas-mozilla** [comment]
I'm not sure how nightly and release data will change what we have. If it's separate tables then we could move per-push over to the generic ingestion.  Using S3+Glue+Athena in our AWS account was very flexible while we were iterating on code, and suspect data hosted elsewhere will be less so.
